// Code generated by "stringer -type=genericErr -linecomment -output=stringers.go"; DO NOT EDIT.

package ppdf

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ErrMissingHeader-1]
	_ = x[ErrMissingStartXref-2]
	_ = x[ErrMalformedStartXref-3]
	_ = x[ErrIncompleteReadAt-4]
	_ = x[ErrOOBXref-5]
	_ = x[ErrCodecMemLimit-6]
	_ = x[ErrCodecDepthLimit-7]
	_ = x[ErrInvalidCodecConfig-8]
	_ = x[errTODO-9]
	_ = x[errValueMismatch-10]
	_ = x[errNameTooLong-11]
	_ = x[_errLexErrorsStart-12]
	_ = x[errXrefStreamBad-13]
	_ = x[errXrefStreamMissingDict-14]
	_ = x[errXrefStreamMissingTok-15]
	_ = x[ErrIllegalToken-16]
	_ = x[errUnexpectedToken-17]
	_ = x[ErrPrevLoop-18]
	_ = x[errPrevChainTooLong-19]
	_ = x[errExpectedXref-20]
	_ = x[errBadSubsectionStart-21]
	_ = x[errExpectingSubsectionOrTrailer-22]
	_ = x[errBadXrefStreamObjectHeader-23]
	_ = x[errUnexpectedEOF-24]
}

const _genericErr_name = "missing %PDF- headermissing startxrefmalformed startxrefReadAt did incomplete readxref offset out of file boundsCodec memory limit hitCodec depth limit hitCodec invalid configPDF feature not implemented yetvalue kind/type mismatchname longer than implementation limitxref stream generic errorxref stream missing dictxref stream missing 'stream' keywordillegal tokenunexpected token/Prev loop found/Prev chain too longexpected 'xref' keywordbad subsection start/entryunexpected token looking for subsections or trailerbad xref stream object headerunexpected end of file"

var _genericErr_index = [...]uint16{0, 20, 37, 56, 82, 112, 134, 155, 175, 206, 230, 267, 267, 292, 316, 352, 365, 381, 397, 417, 440, 466, 517, 546, 568}

func (i genericErr) String() string {
	idx := int(i) - 1
	if i < 1 || idx >= len(_genericErr_index)-1 {
		return "genericErr(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _genericErr_name[_genericErr_index[idx]:_genericErr_index[idx+1]]
}
