// Code generated by "stringer -linecomment -type=FontBuiltin -output=stringers.go"; DO NOT EDIT.

package piupage

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[FontHelvetica-1]
	_ = x[FontHelveticaOblique-2]
	_ = x[FontHelveticaBold-3]
	_ = x[FontHelveticaBoldOblique-4]
	_ = x[FontTimesRoman-5]
	_ = x[FontTimesBold-6]
	_ = x[FontTimesItalic-7]
	_ = x[FontTimesBoldItalic-8]
	_ = x[FontCourier-9]
	_ = x[FontCourierBold-10]
	_ = x[FontCourierOblique-11]
	_ = x[FontCourierBoldOblique-12]
	_ = x[FontSymbol-13]
	_ = x[FontZapfDingbats-14]
}

const _FontBuiltin_name = "HelveticaHelvetica-ObliqueHelvetica-BoldHelvetica-BoldObliqueTimes-RomanTimes-BoldTimes-ItalicTimes-BoldItalicCourierCourier-BoldCourier-ObliqueCourier-BoldObliqueSymbolZapfDingbats"

var _FontBuiltin_index = [...]uint8{0, 9, 26, 40, 61, 72, 82, 94, 110, 117, 129, 144, 163, 169, 181}

func (i FontBuiltin) String() string {
	idx := int(i) - 1
	if i < 1 || idx >= len(_FontBuiltin_index)-1 {
		return "FontBuiltin(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _FontBuiltin_name[_FontBuiltin_index[idx]:_FontBuiltin_index[idx+1]]
}
