// Code generated by "stringer -linecomment -output stringers.go -type=Kind,Token"; DO NOT EDIT.

package piudf

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[KindInvalid-0]
	_ = x[KindNull-1]
	_ = x[KindBool-2]
	_ = x[KindInt-3]
	_ = x[KindReal-4]
	_ = x[KindString-5]
	_ = x[KindHexString-6]
	_ = x[KindName-7]
	_ = x[KindArray-8]
	_ = x[KindDict-9]
	_ = x[KindStream-10]
	_ = x[KindRef-11]
}

const _Kind_name = "invalidnullboolintrealstringhexstringnamearraydictstreamref"

var _Kind_index = [...]uint8{0, 7, 11, 15, 18, 22, 28, 37, 41, 46, 50, 56, 59}

func (i Kind) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_Kind_index)-1 {
		return "Kind(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Kind_name[_Kind_index[idx]:_Kind_index[idx+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[TokUndefined-0]
	_ = x[TokIllegal-1]
	_ = x[TokEOF-2]
	_ = x[TokInt-3]
	_ = x[TokReal-4]
	_ = x[TokName-5]
	_ = x[TokString-6]
	_ = x[TokHexString-7]
	_ = x[TokIdent-8]
	_ = x[TokDictOpen-9]
	_ = x[TokDictClose-10]
	_ = x[TokArrayOpen-11]
	_ = x[TokArrayClose-12]
	_ = x[TokBraceOpen-13]
	_ = x[TokBraceClose-14]
	_ = x[TokR-15]
	_ = x[keywordBeg-16]
	_ = x[TokObj-17]
	_ = x[TokEndobj-18]
	_ = x[TokStream-19]
	_ = x[TokEndstream-20]
	_ = x[TokXref-21]
	_ = x[TokTrailer-22]
	_ = x[TokStartxref-23]
	_ = x[TokTrue-24]
	_ = x[TokFalse-25]
	_ = x[TokNull-26]
	_ = x[keywordEnd-27]
}

const _Token_name = "undefinedillegalEOF<integer><real><name><string><hexstring><identifier><<>>[]{}RkeywordBegobjendobjstreamendstreamxreftrailerstartxreftruefalsenullkeywordEnd"

var _Token_index = [...]uint8{0, 9, 16, 19, 28, 34, 40, 48, 59, 71, 73, 75, 76, 77, 78, 79, 80, 90, 93, 99, 105, 114, 118, 125, 134, 138, 143, 147, 157}

func (i Token) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_Token_index)-1 {
		return "Token(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Token_name[_Token_index[idx]:_Token_index[idx+1]]
}
