// Code generated by "stringer -linecomment -type=Token -output=stringers.go"; DO NOT EDIT.

package piulex

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[TokUndefined-0]
	_ = x[TokIllegal-1]
	_ = x[TokEOF-2]
	_ = x[TokInt-3]
	_ = x[TokReal-4]
	_ = x[TokName-5]
	_ = x[TokString-6]
	_ = x[TokHexString-7]
	_ = x[TokIdent-8]
	_ = x[TokDictOpen-9]
	_ = x[TokDictClose-10]
	_ = x[TokArrayOpen-11]
	_ = x[TokArrayClose-12]
	_ = x[TokBraceOpen-13]
	_ = x[TokBraceClose-14]
	_ = x[TokR-15]
	_ = x[keywordBeg-16]
	_ = x[TokObj-17]
	_ = x[TokEndobj-18]
	_ = x[TokStream-19]
	_ = x[TokEndstream-20]
	_ = x[TokXref-21]
	_ = x[TokTrailer-22]
	_ = x[TokStartxref-23]
	_ = x[TokFalse-24]
	_ = x[TokTrue-25]
	_ = x[TokNull-26]
	_ = x[keywordEnd-27]
}

const _Token_name = "undefinedillegalEOF<integer><real><name><string><hexstring><identifier><<>>[]{}RkeywordBegobjendobjstreamendstreamxreftrailerstartxreffalsetruenullkeywordEnd"

var _Token_index = [...]uint8{0, 9, 16, 19, 28, 34, 40, 48, 59, 71, 73, 75, 76, 77, 78, 79, 80, 90, 93, 99, 105, 114, 118, 125, 134, 139, 143, 147, 157}

func (i Token) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_Token_index)-1 {
		return "Token(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Token_name[_Token_index[idx]:_Token_index[idx+1]]
}
